server:
  port: 80

logging:
  level:
   - dev.ksc : info

mybatis:
  type-aliases-package: dev.ksc.
  mapper-locations: classpath:mybatis/mappers/**/*.xml
spring:
  datasource:
    url: jdbc:mysql://192.168.147.25:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ksc
    password: ksc
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  thymeleaf:
    enabled: true #开启thymeleaf视图解析
    encoding: utf-8
    mode: HTML #严格的HTML语法模式
    cache: false  #是否使用缓存，开发模式建议关闭
    check-template-location: true
    check-template: true
  rabbitmq:
    host: ${app.localhost}
    port: ${app.mq.port}
    username: ${app.mq.username}
    password: ${app.mq.pwd}
    virtual-host: /


app:
  localhost: 192.168.147.25
  mysql:
    port: 3306
    username: ksc
    pwd: ksc
  redis:
    port: 6379
    pwd: 123456
  mq:
    port: 5672
    username: admin
    pwd: admin